### ISSUE TITLE
Why the p4team folder?

### ISSUE THREAD

**Issue by TheZ3ro** [p4-team/crypto-commons#1]
I really like the aim of this project. I was thinking of building one by myself and then I found this.

Anyway, why the main folder is called p4team? Is this some kind of "private"/"exclusive" software?
I think that this library should be "team"-less as I'm willing to help writing some code.

Another question, classic cipher code (like Kasisky over Vigenere, Playfair Enc/Dec) is in the scope of this library or it's Modern Crypto only?

Thanks

**Comment by Pharisaeus** [comment]
Good point. I pushed it like that because this was how I had this on my PC, but it makes sense to get rid of this top level directory if someone else wants to use/develop this. I will fix it!

As for other crypto, I don't think there should be any restrictions. It's just that modern crypto is much more common on CTFs, so most of the stuff I could put there to begin with were related to that. 

However, keep in mind that the goal is not to make a generic cryptography library, and by no means a library anyone should actually use for some real-life scenarios! So a lot of the encryption/decryption code there is either "special cases" or just for the sake of some common attacks.

**Comment by TheZ3ro** [comment]
Yes I agree about the real world implementation. Maybe you should state it in the Readme so people don't get too confused.

**Comment by Pharisaeus** [comment]
I changed the directory structure and extended the readme to make it more clear what is and what is not the purpose.
